# Generated by Django 3.2.9 on 2022-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FREE'), (2, 'SILVER'), (3, 'GOLD')], default=1),
        ),
    ]
