# Generated by Django 3.2.9 on 2021-12-31 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='calendar',
        ),
        migrations.AddField(
            model_name='babysittercalendar',
            name='babysitter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babysitter.babysitter'),
        ),
    ]
