# Generated by Django 3.2.9 on 2022-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0002_auto_20211231_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='home_job',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='car',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='children_with_special_needs',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='cooking',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='driver_license',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='house',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='own_children',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='pets',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='school_activities',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=5),
        ),
    ]
