# Generated by Django 3.2.9 on 2022-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0003_auto_20220101_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='hourly_rate_currency',
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
