# Generated by Django 3.2.9 on 2022-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0004_auto_20220102_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='car',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='children_with_special_needs',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='cooking',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='driver_license',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='home_job',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='house',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='own_children',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='pets',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='school_activities',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
    ]
