# Generated by Django 3.2.9 on 2022-01-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0005_auto_20220103_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='driver_license',
            new_name='sick_child',
        ),
        migrations.AddField(
            model_name='babysitter',
            name='travel',
            field=models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], default='Ne', max_length=5),
        ),
    ]
