# Generated by Django 3.2.9 on 2022-01-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0006_auto_20220121_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Bebisiter', 'Bebisiter'), ('Dadilja', 'Dadilja'), ('Bebisiter i Dadilja', 'Bebisiter i Dadilja')], max_length=50, null=True),
        ),
    ]
