# Generated by Django 3.2.9 on 2022-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0008_alter_babysitter_age_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Bebisiterka', 'Bebisiterka'), ('Dadilja', 'Dadilja'), ('Bebisiterka i Dadilja', 'Bebisiterka i Dadilja')], max_length=50, null=True),
        ),
    ]
