# Generated by Django 3.2.9 on 2022-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0009_alter_babysitter_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='years_care_experience',
            field=models.CharField(blank=True, choices=[('Nemam iskustva u radu sa decom', 'Nemam iskustva u radu sa decom'), ('Imam do godinu dana iskustva u radu sa decom', 'Imam do godinu dana iskustva u radu sa decom'), ('Imam više od godinu dana iskustva u radu sa decom', 'Imam više od godinu dana iskustva u radu sa decom')], max_length=255, null=True),
        ),
    ]
