# Generated by Django 3.2.9 on 2022-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0010_alter_babysitter_years_care_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='years_care_experience',
            field=models.CharField(blank=True, choices=[('Nemam iskustva', 'Nemam iskustva'), ('Do godinu dana', 'Do godinu dana'), ('Više od godinu dana', 'Više od godinu dana')], max_length=255, null=True),
        ),
    ]
