# Generated by Django 3.2.9 on 2022-02-06 13:27

import babysitter.models
import django.core.validators
from django.db import migrations, models
import family.validators
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0011_alter_babysitter_years_care_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='picture',
            field=models.ImageField(blank=True, default='no_face.png', help_text='Slika ne sme biti veća od 2Mb i mora biti formata jpg,png ili jpeg', null=True, upload_to=functools.partial(babysitter.models.make_filepath, *('image',), **{}), validators=[family.validators.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
