# Generated by Django 3.2.9 on 2022-02-25 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitter', '0012_alter_babysitter_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='citizenship',
            field=models.CharField(choices=[('Srpski Državljanin', 'Srpski Državljanin'), ('Strani Državljanin', 'Strani Državljanin')], default='Srpski Drzavljanin', max_length=50),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, default=250, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
