# Generated by Django 3.2.9 on 2021-12-28 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import family.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_monday', models.BooleanField(default=False)),
                ('morning_tuesday', models.BooleanField(default=False)),
                ('morning_wednesday', models.BooleanField(default=False)),
                ('morning_thursday', models.BooleanField(default=False)),
                ('morning_friday', models.BooleanField(default=False)),
                ('morning_saturday', models.BooleanField(default=False)),
                ('morning_sunday', models.BooleanField(default=False)),
                ('afternoon_monday', models.BooleanField(default=False)),
                ('afternoon_tuesday', models.BooleanField(default=False)),
                ('afternoon_wednesday', models.BooleanField(default=False)),
                ('afternoon_thursday', models.BooleanField(default=False)),
                ('afternoon_friday', models.BooleanField(default=False)),
                ('afternoon_saturday', models.BooleanField(default=False)),
                ('afternoon_sunday', models.BooleanField(default=False)),
                ('evening_monday', models.BooleanField(default=False)),
                ('evening_tuesday', models.BooleanField(default=False)),
                ('evening_wednesday', models.BooleanField(default=False)),
                ('evening_thursday', models.BooleanField(default=False)),
                ('evening_friday', models.BooleanField(default=False)),
                ('evening_saturday', models.BooleanField(default=False)),
                ('evening_sunday', models.BooleanField(default=False)),
                ('night_monday', models.BooleanField(default=False)),
                ('night_tuesday', models.BooleanField(default=False)),
                ('night_wednesday', models.BooleanField(default=False)),
                ('night_thursday', models.BooleanField(default=False)),
                ('night_friday', models.BooleanField(default=False)),
                ('night_saturday', models.BooleanField(default=False)),
                ('night_sunday', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('about_me', models.TextField(blank=True)),
                ('about_me_eng', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, default='no_face.png', help_text='Slika ne sme biti veća od 2Mb i mora biti formata jpg,png ili jpeg', null=True, upload_to='img/family', validators=[family.validators.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('sity', models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('Novi Sad', 'Novi Sad'), ('Niš', 'Niš'), ('Kragujevac', 'Kragujevac'), ('Leskovac', 'Leskovac'), ('Ada', 'Ada'), ('Aleksandrovac', 'Aleksandrovac'), ('Aleksinac', 'Aleksinac'), ('Alibunar', 'Alibunar'), ('Apatin', 'Apatin'), ('Aranđelovac', 'Aranđelovac'), ('Arilje', 'Arilje'), ('Babušnica', 'Babušnica'), ('Bač', 'Bač'), ('Bačka Palanka', 'Bačka Palanka'), ('Bačka Topola', 'Bačka Topola'), ('Bački Petrovac', 'Bački Petrovac'), ('Bajina Bašta', 'Bajina Bašta'), ('Batočina', 'Batočina'), ('Bečej', 'Bečej'), ('Bela Crkva', 'Bela Crkva'), ('Bela Palanka', 'Bela Palanka'), ('Beočin', 'Beočin'), ('Blace', 'Blace'), ('Bogatić', 'Bogatić'), ('Bojnik', 'Bojnik'), ('Boljevac', 'Boljevac'), ('Bor', 'Bor'), ('Bosilegrad', 'Bosilegrad'), ('Brus', 'Brus'), ('Bujanovac', 'Bujanovac'), ('Čačak', 'Čačak'), ('Čajetina', 'Čajetina'), ('Ćićevac', 'Ćićevac'), ('Čoka', 'Čoka'), ('Crna Trava', 'Crna Trava'), ('Ćuprija', 'Ćuprija'), ('Despotovac', 'Despotovac'), ('Dimitrovgrad', 'Dimitrovgrad'), ('Doljevac', 'Doljevac'), ('Gadžin Han', 'Gadžin Han'), ('Golubac', 'Golubac'), ('Gornji Milanovac', 'Gornji Milanovac'), ('Inđija', 'Inđija'), ('Irig', 'Irig'), ('Ivanjica', 'Ivanjica'), ('Jagodina', 'Jagodina'), ('Kanjiža', 'Kanjiža'), ('Kikinda', 'Kikinda'), ('Kladovo', 'Kladovo'), ('Knić', 'Knić'), ('Knjaževac', 'Knjaževac'), ('Koceljeva', 'Koceljeva'), ('Kosjerić', 'Kosjerić'), ('Kovačica', 'Kovačica'), ('Kovin', 'Kovin'), ('Kraljevo', 'Kraljevo'), ('Krupanj', 'Krupanj'), ('Kruševac', 'Kruševac'), ('Kučevo', 'Kučevo'), ('Kula', 'Kula'), ('Kuršumlija', 'Kuršumlija'), ('Lajkovac', 'Lajkovac'), ('Lapovo', 'Lapovo'), ('Lebane', 'Lebane'), ('Ljig', 'Ljig'), ('Ljubovija', 'Ljubovija'), ('Loznica', 'Loznica'), ('Lučani', 'Lučani'), ('Majdanpek', 'Majdanpek'), ('Mali Iđoš', 'Mali Iđoš'), ('Mali Zvornik', 'Mali Zvornik'), ('Malo Crniće', 'Malo Crniće'), ('Medveđa', 'Medveđa'), ('Merošina', 'Merošina'), ('Mionica', 'Mionica'), ('Negotin', 'Negotin'), ('Nova Crnja', 'Nova Crnja'), ('Nova Varoš', 'Nova Varoš'), ('Novi Bečej', 'Novi Bečej'), ('Novi Kneževac', 'Novi Kneževac'), ('Novi Pazar', 'Novi Pazar'), ('Odžaci', 'Odžaci'), ('Opovo', 'Opovo'), ('Osečina', 'Osečina'), ('Pančevo', 'Pančevo'), ('Paraćin', 'Paraćin'), ('Pećinci', 'Pećinci'), ('Petrovac na Mlavi', 'Petrovac na Mlavi'), ('Pirot', 'Pirot'), ('Plandište', 'Plandište'), ('Požarevac', 'Požarevac'), ('Požega', 'Požega'), ('Preševo', 'Preševo'), ('Priboj', 'Priboj'), ('Prijepolje', 'Prijepolje'), ('Prokuplje', 'Prokuplje'), ('Rača', 'Rača'), ('Raška', 'Raška'), ('Ražanj', 'Ražanj'), ('Rekovac', 'Rekovac'), ('Ruma', 'Ruma'), ('Šabac', 'Šabac'), ('Sečanj', 'Sečanj'), ('Senta', 'Senta'), ('Šid', 'Šid'), ('Sjenica', 'Sjenica'), ('Smederevo', 'Smederevo'), ('Smederevska Palanka', 'Smederevska Palanka'), ('Sokobanja', 'Sokobanja'), ('Sombor', 'Sombor'), ('Srbobran', 'Srbobran'), ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Sremski Karlovci', 'Sremski Karlovci'), ('Stara Pazova', 'Stara Pazova'), ('Subotica', 'Subotica'), ('Surdulica', 'Surdulica'), ('Svilajnac', 'Svilajnac'), ('Svrljig', 'Svrljig'), ('Temerin', 'Temerin'), ('Titel', 'Titel'), ('Topola', 'Topola'), ('Trgovište', 'Trgovište'), ('Trstenik', 'Trstenik'), ('Tutin', 'Tutin'), ('Ub', 'Ub'), ('Užice', 'Užice'), ('Valjevo', 'Valjevo'), ('Varvarin', 'Varvarin'), ('Velika Plana', 'Velika Plana'), ('Veliko Gradište', 'Veliko Gradište'), ('Vladičin Han', 'Vladičin Han'), ('Vladimirci', 'Vladimirci'), ('Vlasotince', 'Vlasotince'), ('Vranje', 'Vranje'), ('Vrbas', 'Vrbas'), ('Vrnjačka Banja', 'Vrnjačka Banja'), ('Vršac', 'Vršac'), ('Žabalj', 'Žabalj'), ('Žabari', 'Žabari'), ('Žagubica', 'Žagubica'), ('Zaječar', 'Zaječar'), ('Žitište', 'Žitište'), ('Žitorađa', 'Žitorađa'), ('Zrenjanin', 'Zrenjanin')], max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text="Koristi sledeći format: '+381641234567'", max_length=17, validators=[django.core.validators.RegexValidator(message='Broj nije u odgovarajućem formatu, +381641234567', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('social_network', models.URLField(blank=True, max_length=225, null=True)),
                ('number_children', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('10+', '10+')], default='2', max_length=5)),
                ('age_children', models.CharField(choices=[('0-1', '0-1'), ('1-3', '1-3'), ('3-5', '3-5'), ('5-12', '5-12'), ('12-18', '12-18')], default='1-3', max_length=10)),
                ('citizenship', models.CharField(choices=[('Srpski Drzavljanin', 'Srpski Drzavljanin'), ('Strani Drzavljanin', 'Strani Drzavljanin')], default='Srpski Drzavljanin', max_length=50)),
                ('is_form_submit', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.familycalendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
