# Generated by Django 3.2.9 on 2021-12-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
