# Generated by Django 3.2.9 on 2021-12-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.familycalendar'),
        ),
    ]
