# Generated by Django 3.2.9 on 2022-01-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20211229_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='childcare_period',
            field=models.CharField(choices=[('Manje od mesec dana', 'Manje od mesec dana'), ('Mesec dana', 'Mesec dana'), ('Par meseci', 'Par meseci'), ('Godinu dana', 'Godinu dana'), ('Više od godinu dana', 'Više od godinu dana')], default='Mesec dana', max_length=50),
        ),
    ]
