# Generated by Django 3.2.9 on 2022-01-22 22:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_family_childcare_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='age_children',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0-1', '0-1'), ('1-3', '1-3'), ('3-5', '3-5'), ('5-12', '5-12'), ('12-18', '12-18')], default='1-3', max_length=22),
        ),
    ]
