# Generated by Django 3.2.9 on 2022-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_alter_family_age_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='number_children',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='2', max_length=5),
        ),
    ]
