# Generated by Django 3.2.9 on 2022-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_alter_family_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childcare_period',
            field=models.CharField(choices=[('Povremeno', 'Povremeno'), ('Manje od mesec dana', 'Manje od mesec dana'), ('Mesec dana', 'Mesec dana'), ('Par meseci', 'Par meseci'), ('Godinu dana', 'Godinu dana'), ('Više od godinu dana', 'Više od godinu dana')], default='Mesec dana', max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='citizenship',
            field=models.CharField(choices=[('Srpski Državljanin', 'Srpski Državljanin'), ('Strani Državljanin', 'Strani Državljanin')], default='Srpski Drzavljanin', max_length=50),
        ),
    ]
