# Generated by Django 3.2.9 on 2022-01-31 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_of_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_report', to=settings.AUTH_USER_MODEL)),
                ('reported_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_of_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_rate', to=settings.AUTH_USER_MODEL)),
                ('rated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary_body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_of_commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_commentary', to=settings.AUTH_USER_MODEL)),
                ('commentated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentated_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
