# Generated by Django 3.2.9 on 2022-02-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0009_auto_20220225_2005'),
        ('babysitter', '0013_auto_20220225_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter_favorite', to='babysitter.babysitter')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_favorite', to='family.family')),
            ],
        ),
    ]
