# Generated by Django 3.2.9 on 2022-01-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babysitter', '0008_alter_babysitter_age_children'),
        ('family', '0005_family_childcare_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_matched', models.BooleanField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter_match', to='babysitter.babysitter')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_match', to='family.family')),
            ],
        ),
    ]
